yarnPath: .yarn/releases/yarn-4.7.0.cjs
nodeLinker: node-modules
npmScopes:
  tmax:
    npmRegistryServer: "http://192.168.11.20:8081/repository/Tmax_Design_System_0.0.0/"

unsafeHttpWhitelist:
  - "192.168.11.20"